### namespace


---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-nginx

###  channel
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: namespace-nginx
  namespace: namespace-nginx
spec:
    type: Namespace
    pathname: namespace-nginx

# Deployable
---
  apiVersion: apps.open-cluster-management.io/v1
  kind: Deployable
  metadata:
    annotations:
      apps.open-cluster-management.io/is-local-deployable: "false"
    name: namespace-nginx
    namespace: namespace-nginx
  spec:
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: nginx
        name: nginx-deployment
        namespace: namespace-nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: bitnami/nginx:1.16.1
              ports:
              - containerPort: 8080


# Subscription
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: namespace-nginx
  namespace: namespace-nginx
  labels:
    app: nginx

spec:
  channel: namespace-nginx/namespace-nginx
  name: namespace-nginx
  namespace: namespace-nginx
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-placement    

# Application
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: namespace-nginx
  namespace: namespace-nginx                     
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:    
        - nginx

# placement rule

---

apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-placement
  namespace: namespace-nginx
spec:
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: dev
