apiVersion: v1
kind: Pod
metadata:
  name: opa-disallowed
  namespace: disallow-image
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:latest
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
