apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: disallow-latest-image
  namespace: disallow-latest
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: disallow-latest-image-constraint-template
      spec:
        remediationAction: enforce # will be overridden by remediationAction in parent policy
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
               apiVersion: templates.gatekeeper.sh/v1beta1
               kind: ConstraintTemplate
               metadata:
                 name: k8sdisallowedtags
                 annotations:
                   description: Requires container images to have an image tag different from the ones in a specified list.
               spec:
                 crd:
                   spec:
                     names:
                       kind: K8sDisallowedTags
                     validation:
                       # Schema for the `parameters` field
                       openAPIV3Schema:
                         properties:
                           tags:
                             type: array
                             items:
                               type: string
                 targets:
                   - target: admission.k8s.gatekeeper.sh
                     rego: |
                       package k8sdisallowedtags
               
                       violation[{"msg": msg}] {
                         container := input_containers[_]
                         tags := [forbid | tag = input.parameters.tags[_] ; forbid = endswith(container.image, concat(":", ["", tag]))]
                         any(tags)
                         msg := sprintf("container <%v> uses a disallowed tag <%v>; disallowed tags are %v", [container.name, container.image, input.parameters.tags])
                       }
               
                       violation[{"msg": msg}] {
                         container := input_containers[_]
                         tag := [contains(container.image, ":")]
                         not all(tag)
                         msg := sprintf("container <%v> didn't specify an image tag <%v>", [container.name, container.image])
                       }
               
                       input_containers[c] {
                         c := input.review.object.spec.containers[_]
                       }
                       input_containers[c] {
                         c := input.review.object.spec.initContainers[_]
                       }
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: disallow-latest-image-constraint
      spec:
        remediationAction: enforce # will be overridden by remediationAction in parent policy
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
               apiVersion: constraints.gatekeeper.sh/v1beta1
               kind: K8sDisallowedTags
               metadata:
                 name: container-image-must-not-have-latest-tag
               spec:
                 match:
                   kinds:
                     - apiGroups: [""]
                       kinds: ["Pod"]
                   namespaces:
                     - "default"
                 parameters:
                   tags: ["latest"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-disallow-latest-image
  namespace: disallow-latest
placementRef:
  name: placement-policy-disallow-latest-image
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: disallow-latest-image
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-disallow-latest-image
  namespace: disallow-latest
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}
