apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-quota-limit-demo
  namespace: quota-demo
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: resource-quota-object
      spec:
        remediationAction: enforce # will be overridden by remediationAction in parent policy
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
               apiVersion: v1
               kind: ResourceQuota
               namespace: quota-demo
               metadata:
                 name: compute-resources
               spec:
                 hard:
                   pods: "4" 
                   requests.cpu: "1" 
                   requests.memory: 1Gi 
                   requests.ephemeral-storage: 2Gi 
                   limits.cpu: "2" 
                   limits.memory: 2Gi 
                   limits.ephemeral-storage: 4Gi 
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-quota-limit-demo
  namespace: quota-demo
placementRef:
  name: placement-policy-quota-limit-demo
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-quota-limit-demo
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-quota-limit-demo
  namespace: quota-demo
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}
